const dotenv = require('dotenv');
dotenv.config();
const {
  GOOGLE_CALENDAR_TYPE,
  GOOGLE_CALENDAR_CLIENT_ID, 
  GOOGLE_CALENDAR_PROJECT_ID, 
  GOOGLE_CALENDAR_AUTH_URI, 
  GOOGLE_CALENDAR_TOKEN_URI, 
  GOOGLE_CALENDAR_CERT_URL,
  GOOGLE_CALENDAR_PRIVATE_KEY_ID,
  GOOGLE_CALENDAR_AUTH_CERT_URL,
  GOOGLE_CALENDAR_PRIVATE_KEY,
  GOOGLE_CALENDAR_CLIENT_EMAIL} = process.env;

module.exports = {
  "type": GOOGLE_CALENDAR_TYPE,
  "project_id": GOOGLE_CALENDAR_PROJECT_ID,
  "private_key_id": GOOGLE_CALENDAR_PRIVATE_KEY_ID,
  "private_key": GOOGLE_CALENDAR_PRIVATE_KEY,
  "client_email": GOOGLE_CALENDAR_CLIENT_EMAIL,
  "client_id": GOOGLE_CALENDAR_CLIENT_ID,
  "auth_uri": GOOGLE_CALENDAR_AUTH_URI,
  "token_uri": GOOGLE_CALENDAR_TOKEN_URI,
  "auth_provider_x509_cert_url": GOOGLE_CALENDAR_AUTH_CERT_URL,
  "client_x509_cert_url": GOOGLE_CALENDAR_CERT_URL
};
